#! /usr/bin/perl
use strict;
use warnings;
use Sys::Hostname;

# k means black background, d means default
my $bg = "d";

my $host = hostname;
$host =~ s/\..*$//;
my $PROD = $ENV{SCREEN_NAME_IS_PROD} ? "\005{rk}PROD " : ""; 
my $color;
if ($ENV{SCREEN_NAME_COLOR}) {
    $color = $ENV{SCREEN_NAME_COLOR};
}
else {
    ## semi-randomly pick a color. This is not perfect, but might
    ## be just enough

    ## you can also specify hex values, but I'm not sure
    ## about collisions on 'b' 'c' and 'd'
    my @colors = qw( r g y b m c w );
    my $count = 0;
    map { $count += $_ } unpack "C*", $host;
    my $pick = $colors[ $count % scalar @colors];

    $color = "$bg$pick";
}

print "${PROD}\005{=b $color}$host";
